hGem.WebUI/ViewModels/TextResources/TextResourcePageViewModel.cs
namespace hGem.WebUI.ViewModels.TextResources
{
    public class TextResourcePageViewModel
    {
    }
}

hGem.WebUI/ViewModels/TextResources/TextResourceViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace hGem.WebUI.ViewModels.TextResources
{
    public class TextResourceViewModel
    {
        public int TextResourceId { get; set; }

        [Required]
        public string TextResourceString { get; set; }

        [Required]
        public string TextResourceCode { get; set; }

        [Required]
        public int LanguageId { get; set; }

        [Required]
        public bool ClientOverride { get; set; }

        //public bool ForceAdd { get; set; }
    }
}

hGem.WebUI/Controllers/TextResourceController.cs
using System.Web.Mvc;
using hGem.Core.Infrastructure.AutoMapper;
using hGem.Core.Services.TextResourceService;
using hGem.WebUI.ViewModels.TextResources;

namespace hGem.WebUI.Controllers
{
    public partial class TextResourceController : Controller
    {
        private readonly IObjectMapper _objectMapper;
        private readonly ITextResourceService _textResourceService;

        public TextResourceController(IObjectMapper objectMapper, ITextResourceService textResourceService)
        {
            _objectMapper = objectMapper;
            _textResourceService = textResourceService;
        }

        public virtual ActionResult Index(TextResourcePageViewModel model)
        {
            return View(model);
        }

        //[HttpPost, Route("create")]
        //public ActionResult Create(TextResourceViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var dto = _mappingEngine.Map<TextResourceViewModel, SaveTextResourceDto>(model);

        //        _textResourceService.SaveResource(dto);

        //        return RedirectToAction("View", new { textResourceId = dto.LanguageId });
        //    }
        //    return View(model);
        //}

        //[HttpGet, Route("{TextResourceId:int}")]
        //public ActionResult View(int textResourceId)
        //{
        //    var textResource = _textResourceService.GetTextResource(textResourceId);

        //    var viewModel = _mappingEngine.Map<TextResourceDto, TextResourceViewModel>(textResource);

        //    return View(viewModel);
        //}
    }
}

hGem.WebUI/Views/TextResource/Create.cshtml
@model Warp.WebUI.Models.TextResources.TextResourceViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TextResouceViewModel</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.TextResourceString, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TextResourceString)
                @Html.ValidationMessageFor(model => model.TextResourceString)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TextResourceCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TextResourceCode)
                @Html.ValidationMessageFor(model => model.TextResourceCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LanguageId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LanguageId)
                @Html.ValidationMessageFor(model => model.LanguageId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientOverride, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientOverride)
                @Html.ValidationMessageFor(model => model.ClientOverride)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

hGem.WebUI/Views/TextResource/Index.cshtml
@model Warp.WebUI.Models.TextResources.TextResourcePageViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

hGem.WebUI/Views/TextResource/View.cshtml
@model Warp.WebUI.Models.TextResources.TextResourceViewModel

@{ ViewBag.Title = Model.TextResourceCode; }
@using (Html.BeginForm("Create", "TextResource", FormMethod.Post, new {Model.TextResourceId}))
{
    <div>Resource Id: @Html.DisplayFor(m => Model.TextResourceId)</div>
    <div>Resource String: @Html.EditorFor(model => model.TextResourceString)</div>
    <div>Resource Code: @Html.EditorFor(model => model.TextResourceCode)</div>
    <div>Language Id: @Html.EditorFor(model => model.LanguageId)</div>
    <div>Client Override: @Html.EditorFor(model => Model.ClientOverride)</div>
}
<input type="submit" value="Update"/>